/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangPublicRouteRouteImport } from './routes/$lang/_public/route'
import { Route as LangPrivateRouteRouteImport } from './routes/$lang/_private/route'
import { Route as LangPublicSignUpRouteImport } from './routes/$lang/_public/sign-up'
import { Route as LangPublicSignInRouteImport } from './routes/$lang/_public/sign-in'
import { Route as LangPrivateColaborandoRouteImport } from './routes/$lang/_private/colaborando'
import { Route as LangPrivatePagePageIdRouteImport } from './routes/$lang/_private/page/$pageId'
import { Route as LangPrivateMyworkspaceWorkspaceIdRouteImport } from './routes/$lang/_private/myworkspace/$workspaceId'

const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPublicRouteRoute = LangPublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPrivateRouteRoute = LangPrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPublicSignUpRoute = LangPublicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => LangPublicRouteRoute,
} as any)
const LangPublicSignInRoute = LangPublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => LangPublicRouteRoute,
} as any)
const LangPrivateColaborandoRoute = LangPrivateColaborandoRouteImport.update({
  id: '/colaborando',
  path: '/colaborando',
  getParentRoute: () => LangPrivateRouteRoute,
} as any)
const LangPrivatePagePageIdRoute = LangPrivatePagePageIdRouteImport.update({
  id: '/page/$pageId',
  path: '/page/$pageId',
  getParentRoute: () => LangPrivateRouteRoute,
} as any)
const LangPrivateMyworkspaceWorkspaceIdRoute =
  LangPrivateMyworkspaceWorkspaceIdRouteImport.update({
    id: '/myworkspace/$workspaceId',
    path: '/myworkspace/$workspaceId',
    getParentRoute: () => LangPrivateRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/colaborando': typeof LangPrivateColaborandoRoute
  '/$lang/sign-in': typeof LangPublicSignInRoute
  '/$lang/sign-up': typeof LangPublicSignUpRoute
  '/$lang/myworkspace/$workspaceId': typeof LangPrivateMyworkspaceWorkspaceIdRoute
  '/$lang/page/$pageId': typeof LangPrivatePagePageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/colaborando': typeof LangPrivateColaborandoRoute
  '/$lang/sign-in': typeof LangPublicSignInRoute
  '/$lang/sign-up': typeof LangPublicSignUpRoute
  '/$lang/myworkspace/$workspaceId': typeof LangPrivateMyworkspaceWorkspaceIdRoute
  '/$lang/page/$pageId': typeof LangPrivatePagePageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/_private': typeof LangPrivateRouteRouteWithChildren
  '/$lang/_public': typeof LangPublicRouteRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/_private/colaborando': typeof LangPrivateColaborandoRoute
  '/$lang/_public/sign-in': typeof LangPublicSignInRoute
  '/$lang/_public/sign-up': typeof LangPublicSignUpRoute
  '/$lang/_private/myworkspace/$workspaceId': typeof LangPrivateMyworkspaceWorkspaceIdRoute
  '/$lang/_private/page/$pageId': typeof LangPrivatePagePageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/$lang/colaborando'
    | '/$lang/sign-in'
    | '/$lang/sign-up'
    | '/$lang/myworkspace/$workspaceId'
    | '/$lang/page/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/$lang/colaborando'
    | '/$lang/sign-in'
    | '/$lang/sign-up'
    | '/$lang/myworkspace/$workspaceId'
    | '/$lang/page/$pageId'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/_private'
    | '/$lang/_public'
    | '/$lang/'
    | '/$lang/_private/colaborando'
    | '/$lang/_public/sign-in'
    | '/$lang/_public/sign-up'
    | '/$lang/_private/myworkspace/$workspaceId'
    | '/$lang/_private/page/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/_public': {
      id: '/$lang/_public'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangPublicRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/_private': {
      id: '/$lang/_private'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangPrivateRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/_public/sign-up': {
      id: '/$lang/_public/sign-up'
      path: '/sign-up'
      fullPath: '/$lang/sign-up'
      preLoaderRoute: typeof LangPublicSignUpRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/sign-in': {
      id: '/$lang/_public/sign-in'
      path: '/sign-in'
      fullPath: '/$lang/sign-in'
      preLoaderRoute: typeof LangPublicSignInRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_private/colaborando': {
      id: '/$lang/_private/colaborando'
      path: '/colaborando'
      fullPath: '/$lang/colaborando'
      preLoaderRoute: typeof LangPrivateColaborandoRouteImport
      parentRoute: typeof LangPrivateRouteRoute
    }
    '/$lang/_private/page/$pageId': {
      id: '/$lang/_private/page/$pageId'
      path: '/page/$pageId'
      fullPath: '/$lang/page/$pageId'
      preLoaderRoute: typeof LangPrivatePagePageIdRouteImport
      parentRoute: typeof LangPrivateRouteRoute
    }
    '/$lang/_private/myworkspace/$workspaceId': {
      id: '/$lang/_private/myworkspace/$workspaceId'
      path: '/myworkspace/$workspaceId'
      fullPath: '/$lang/myworkspace/$workspaceId'
      preLoaderRoute: typeof LangPrivateMyworkspaceWorkspaceIdRouteImport
      parentRoute: typeof LangPrivateRouteRoute
    }
  }
}

interface LangPrivateRouteRouteChildren {
  LangPrivateColaborandoRoute: typeof LangPrivateColaborandoRoute
  LangPrivateMyworkspaceWorkspaceIdRoute: typeof LangPrivateMyworkspaceWorkspaceIdRoute
  LangPrivatePagePageIdRoute: typeof LangPrivatePagePageIdRoute
}

const LangPrivateRouteRouteChildren: LangPrivateRouteRouteChildren = {
  LangPrivateColaborandoRoute: LangPrivateColaborandoRoute,
  LangPrivateMyworkspaceWorkspaceIdRoute:
    LangPrivateMyworkspaceWorkspaceIdRoute,
  LangPrivatePagePageIdRoute: LangPrivatePagePageIdRoute,
}

const LangPrivateRouteRouteWithChildren =
  LangPrivateRouteRoute._addFileChildren(LangPrivateRouteRouteChildren)

interface LangPublicRouteRouteChildren {
  LangPublicSignInRoute: typeof LangPublicSignInRoute
  LangPublicSignUpRoute: typeof LangPublicSignUpRoute
}

const LangPublicRouteRouteChildren: LangPublicRouteRouteChildren = {
  LangPublicSignInRoute: LangPublicSignInRoute,
  LangPublicSignUpRoute: LangPublicSignUpRoute,
}

const LangPublicRouteRouteWithChildren = LangPublicRouteRoute._addFileChildren(
  LangPublicRouteRouteChildren,
)

interface LangRouteRouteChildren {
  LangPrivateRouteRoute: typeof LangPrivateRouteRouteWithChildren
  LangPublicRouteRoute: typeof LangPublicRouteRouteWithChildren
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangPrivateRouteRoute: LangPrivateRouteRouteWithChildren,
  LangPublicRouteRoute: LangPublicRouteRouteWithChildren,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
