/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangAppRouteImport } from './routes/$lang.app'
import { Route as LangPublicRouteImport } from './routes/$lang._public'
import { Route as LangAppIndexRouteImport } from './routes/$lang.app.index'
import { Route as LangPublicSignUpRouteImport } from './routes/$lang._public.sign-up'
import { Route as LangPublicSignInRouteImport } from './routes/$lang._public.sign-in'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangAppRoute = LangAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => LangRoute,
} as any)
const LangPublicRoute = LangPublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => LangRoute,
} as any)
const LangAppIndexRoute = LangAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangAppRoute,
} as any)
const LangPublicSignUpRoute = LangPublicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => LangPublicRoute,
} as any)
const LangPublicSignInRoute = LangPublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => LangPublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/app': typeof LangAppRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/sign-in': typeof LangPublicSignInRoute
  '/$lang/sign-up': typeof LangPublicSignUpRoute
  '/$lang/app/': typeof LangAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/sign-in': typeof LangPublicSignInRoute
  '/$lang/sign-up': typeof LangPublicSignUpRoute
  '/$lang/app': typeof LangAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/_public': typeof LangPublicRouteWithChildren
  '/$lang/app': typeof LangAppRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/_public/sign-in': typeof LangPublicSignInRoute
  '/$lang/_public/sign-up': typeof LangPublicSignUpRoute
  '/$lang/app/': typeof LangAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/app'
    | '/$lang/'
    | '/$lang/sign-in'
    | '/$lang/sign-up'
    | '/$lang/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$lang' | '/$lang/sign-in' | '/$lang/sign-up' | '/$lang/app'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/_public'
    | '/$lang/app'
    | '/$lang/'
    | '/$lang/_public/sign-in'
    | '/$lang/_public/sign-up'
    | '/$lang/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/app': {
      id: '/$lang/app'
      path: '/app'
      fullPath: '/$lang/app'
      preLoaderRoute: typeof LangAppRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_public': {
      id: '/$lang/_public'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangPublicRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/app/': {
      id: '/$lang/app/'
      path: '/'
      fullPath: '/$lang/app/'
      preLoaderRoute: typeof LangAppIndexRouteImport
      parentRoute: typeof LangAppRoute
    }
    '/$lang/_public/sign-up': {
      id: '/$lang/_public/sign-up'
      path: '/sign-up'
      fullPath: '/$lang/sign-up'
      preLoaderRoute: typeof LangPublicSignUpRouteImport
      parentRoute: typeof LangPublicRoute
    }
    '/$lang/_public/sign-in': {
      id: '/$lang/_public/sign-in'
      path: '/sign-in'
      fullPath: '/$lang/sign-in'
      preLoaderRoute: typeof LangPublicSignInRouteImport
      parentRoute: typeof LangPublicRoute
    }
  }
}

interface LangPublicRouteChildren {
  LangPublicSignInRoute: typeof LangPublicSignInRoute
  LangPublicSignUpRoute: typeof LangPublicSignUpRoute
}

const LangPublicRouteChildren: LangPublicRouteChildren = {
  LangPublicSignInRoute: LangPublicSignInRoute,
  LangPublicSignUpRoute: LangPublicSignUpRoute,
}

const LangPublicRouteWithChildren = LangPublicRoute._addFileChildren(
  LangPublicRouteChildren,
)

interface LangAppRouteChildren {
  LangAppIndexRoute: typeof LangAppIndexRoute
}

const LangAppRouteChildren: LangAppRouteChildren = {
  LangAppIndexRoute: LangAppIndexRoute,
}

const LangAppRouteWithChildren =
  LangAppRoute._addFileChildren(LangAppRouteChildren)

interface LangRouteChildren {
  LangPublicRoute: typeof LangPublicRouteWithChildren
  LangAppRoute: typeof LangAppRouteWithChildren
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangPublicRoute: LangPublicRouteWithChildren,
  LangAppRoute: LangAppRouteWithChildren,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
