/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangAppRouteRouteImport } from './routes/$lang/app/route'
import { Route as LangPublicRouteRouteImport } from './routes/$lang/_public/route'
import { Route as LangAppIndexRouteImport } from './routes/$lang/app/index'
import { Route as LangPublicSignUpRouteImport } from './routes/$lang/_public/sign-up'
import { Route as LangPublicSignInRouteImport } from './routes/$lang/_public/sign-in'

const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAppRouteRoute = LangAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPublicRouteRoute = LangPublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAppIndexRoute = LangAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangAppRouteRoute,
} as any)
const LangPublicSignUpRoute = LangPublicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => LangPublicRouteRoute,
} as any)
const LangPublicSignInRoute = LangPublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => LangPublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/app': typeof LangAppRouteRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/sign-in': typeof LangPublicSignInRoute
  '/$lang/sign-up': typeof LangPublicSignUpRoute
  '/$lang/app/': typeof LangAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/sign-in': typeof LangPublicSignInRoute
  '/$lang/sign-up': typeof LangPublicSignUpRoute
  '/$lang/app': typeof LangAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/_public': typeof LangPublicRouteRouteWithChildren
  '/$lang/app': typeof LangAppRouteRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/_public/sign-in': typeof LangPublicSignInRoute
  '/$lang/_public/sign-up': typeof LangPublicSignUpRoute
  '/$lang/app/': typeof LangAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/app'
    | '/$lang/'
    | '/$lang/sign-in'
    | '/$lang/sign-up'
    | '/$lang/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$lang' | '/$lang/sign-in' | '/$lang/sign-up' | '/$lang/app'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/_public'
    | '/$lang/app'
    | '/$lang/'
    | '/$lang/_public/sign-in'
    | '/$lang/_public/sign-up'
    | '/$lang/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/app': {
      id: '/$lang/app'
      path: '/app'
      fullPath: '/$lang/app'
      preLoaderRoute: typeof LangAppRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/_public': {
      id: '/$lang/_public'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangPublicRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/app/': {
      id: '/$lang/app/'
      path: '/'
      fullPath: '/$lang/app/'
      preLoaderRoute: typeof LangAppIndexRouteImport
      parentRoute: typeof LangAppRouteRoute
    }
    '/$lang/_public/sign-up': {
      id: '/$lang/_public/sign-up'
      path: '/sign-up'
      fullPath: '/$lang/sign-up'
      preLoaderRoute: typeof LangPublicSignUpRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/sign-in': {
      id: '/$lang/_public/sign-in'
      path: '/sign-in'
      fullPath: '/$lang/sign-in'
      preLoaderRoute: typeof LangPublicSignInRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
  }
}

interface LangPublicRouteRouteChildren {
  LangPublicSignInRoute: typeof LangPublicSignInRoute
  LangPublicSignUpRoute: typeof LangPublicSignUpRoute
}

const LangPublicRouteRouteChildren: LangPublicRouteRouteChildren = {
  LangPublicSignInRoute: LangPublicSignInRoute,
  LangPublicSignUpRoute: LangPublicSignUpRoute,
}

const LangPublicRouteRouteWithChildren = LangPublicRouteRoute._addFileChildren(
  LangPublicRouteRouteChildren,
)

interface LangAppRouteRouteChildren {
  LangAppIndexRoute: typeof LangAppIndexRoute
}

const LangAppRouteRouteChildren: LangAppRouteRouteChildren = {
  LangAppIndexRoute: LangAppIndexRoute,
}

const LangAppRouteRouteWithChildren = LangAppRouteRoute._addFileChildren(
  LangAppRouteRouteChildren,
)

interface LangRouteRouteChildren {
  LangPublicRouteRoute: typeof LangPublicRouteRouteWithChildren
  LangAppRouteRoute: typeof LangAppRouteRouteWithChildren
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangPublicRouteRoute: LangPublicRouteRouteWithChildren,
  LangAppRouteRoute: LangAppRouteRouteWithChildren,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
